version: "3.8"

services:
  web-app-sandbox:
    build: ./web-app-sandbox
    image: web-sandbox
    ports:
      - 5000:5000
    container_name: saferoute-sandbox

  public-website:
    build: ./front-facing-website
    image: safe-route-public-website
    ports:
      - 5000:5000
    container_name: public-website

  backend-servers-flask:
    restart: unless-stopped
    build: ./backend-servers/flask/server-template/.
    image: flask-server
    ports:
      - 5500:5500
    container_name: saferoute-flask-backend

  jwt-auth-server:
    build: ./jwt-auth-express
    image: express-jwt-auth
    restart: always
    env_file: .env
    ports:
      - 3000:3000
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - WAIT_HOSTS: mongodb:27017
    container_name: jwt-auth

  mongodb:
    image: mongo:4.4.14-focal
    restart: unless-stopped
    volumes:
      - ~/mongo:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=usersdb
      